# Generated by Django 3.2.7 on 2021-12-08 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40, null=True, verbose_name='チームネーム')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時')),
                ('average_rank', models.CharField(max_length=40, verbose_name='ランク')),
                ('map', models.CharField(max_length=40, verbose_name='マップ')),
                ('comment', models.TextField(max_length=200, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
