# Generated by Django 3.2.7 on 2021-12-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='ランク帯')),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='map',
        ),
        migrations.AddField(
            model_name='board',
            name='map',
            field=models.ManyToManyField(max_length=40, to='valorant.Rank', verbose_name='マップ'),
        ),
    ]
