# Generated by Django 3.2.7 on 2021-12-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0002_auto_20211223_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='average_rank',
        ),
        migrations.AddField(
            model_name='board',
            name='average_rank',
            field=models.ManyToManyField(max_length=40, to='valorant.Rank', verbose_name='ランク'),
        ),
        migrations.RemoveField(
            model_name='board',
            name='map',
        ),
        migrations.AddField(
            model_name='board',
            name='map',
            field=models.CharField(default=1, max_length=40, verbose_name='マップ'),
            preserve_default=False,
        ),
    ]
